# This is the default submit config
# NOTE: if there are brackets in the line comments in the following config, 
# that means this config only supports words in the bracket, other words dont support
# [dont use]: this option is not used
# [fixed value]: this option is a fixed value, modify this option has no effect

[meta]
project = "demo"                     # [dont use]
author  = "Ben"                      # [dont use]
version = "1.0"                      # [dont use]
notif   = {mail = "", ena = "off"}   # ena: [off on]


[dut]
arch        = "rv64im"               # [rv32e rv32i rv32im rv64i rv64im]
file        = "ysyx_xxxxxxxx.v"      # dut file name
top         = "ysyx_xxxxxxxx"        # top module name
clk         = "clock"                # top clock signal name
commit      = ""                     # ["", "vcs", "dc"]
                                     # leaving a blank means test vcs+dc, otherwise 
                                     # ci only run specific test when 'commit' == test's flag
                                     # example: commit == "dc" means only run dc test
                                     # now iverilog, verilator, yosys and fpga test
                                     # are not supported.

[iverilog]
flag = "iv"                          # commit flag [dont use]

[verilator]
flag = "ver"                         # commit flag [dont use]

[yosys]
flag        = "yosys"                # commit flag [dont use]
freq        = 25                     # [dont use]

[vcs]
flag        = "vcs"                  # commit flag
freq        = 25                     # [dont use]
prog        = {name = "", type = ""} # format: [name]-[type] name: [hello, memtest, rtthread] type: [flash, mem, sdram]
                                     # leave name item a blank means testing all programs
wave        = "off"                  # [off on] note: wave option only valid when prog.name is not a blank and wave is "on"
                                     # now only support prog.name == hello, and prog.type can ben 'flash', 'mem' and 'sdram',
                                     # other combinations dont support if you want to generate wave

[dc]
flag        = "dc"                   # commit flag
process     = "28"                   # [110, 40, 28] [fixed value]
freq        = 100                    # [100, 800, step: 50]
corner      = "MAX"                  # [WCZ MAX WCL TYP MIN ML MZ]
track       = "9T"                   # [8T 9T 10T 11T 12T] [fixed value]
volt_chnl   = "SVT40+LVT40"          # voltage threshold and channel length secletion such as "SVT40+SVT35"
                                     # or "SVT40+LVT35:0.3" to limit ration of LVT35 [fixed value]
retime      = "off"                  # [off on]
user        = ""                     # user report suffix [fixed value]

[ieda]
flag        = "ieda"                 # commit flag [dont use]

[fpga]
flag        = "fpga"                 # commit flag [dont use]
freq        = 25
