# This is the default submit config
# NOTE: below config if have bracket in line comment, that mean 
# this config only supports string in bracket, other words dont support

[meta]
project = "demo"
author  = "Ben"
version = "1.0"

[dut]
arch        = "rv64im"               # [rv32e rv32i rv32im rv64i rv64im]
file        = "ysyx_xxxxxxxx.v"      # dut file name TODO: support filelist
top         = "ysyx_xxxxxxxx"        # top module name
clk         = "clk"                  # top clock signal name
commit      = ""                     # support ["", "vcs", "dc"] leave a blank mean
                                     # test vcs+dc, otherwise ci only run specific test 
                                     # which commit equal below testsuit's flag.
                                     # Now iverilog and verilator test are not supported.
                                     # example: commit == "dc" mean only run dc test

[iverilog]
flag = "iv"                          # commit flag[dont use]

[verilator]
flag = "ver"                         # commit flag[dont use]

[vcs]
flag        = "vcs"                  # commit flag[dont use]
freq        = 25
prog        = {name = "", type = ""} # format: [name]-[type] name: [hello, memtest, rtthread] type: [flash, mem, sdram]
                                     # leave name item a blank mean test all programs
wave        = "off"                  # [off on] note: wave option only valid when prog.name is not a blank and wave is "on"

[dc]
flag        = "dc"                   # flag[dont use]
process     = "28"                   # [110, 40, 28] [fixed value]
freq        = 100                    # [100, 800, step: 50]
corner      = "TYP"                  # [WCZ MAX WCL TYP MIN ML MZ]
track       = "8T"                   # [8T ...] [dont use]
volt_chnl   = "SVT40"                # voltage threshold and channel length secletion such as "SVT40+SVT35"
                                     # or "SVT40+LVT35:0.3" to limit ration of LVT35
retime      = "off"                  # [off on]
user        = ""                     # [dont use]

[fpga]
flag        = "fpga"                 # commit flag[dont use]
freq        = 25
